// counters/react-tutorial/src/views/Counter.tsx
import {useCallback, useEffect, useLayoutEffect, useState} from 'react'
import Button from "./ui/Button.tsx";

function Counter() {
    const [count, setCount] = useState(0)

    const decrement = useCallback(
        () => {
            setCount(count => count - 1)
        },
        []
    )

    const increment = useCallback(
        () => {
            setCount(count => count + 1)
        },
        []
    )

    return (
        <div>
            <Button onClick={decrement}> -</Button>
            <span>{count}</span>
            <Button onClick={increment}> +</Button>
        </div>
    )
}

export default Counter

// samples/counters/angular-tutorial/src/app/counter.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-counter',
  template: `
    <button type="button" (click)="decrement()"> - </button>
    <span>{{ count }}</span>
    <button type="button" (click)="increment()"> + </button>
  `
})
export class CounterComponent {
  count = 0;

  decrement() {
    this.count--;
  }

  increment() {
    this.count++;
  }
}
