// counters/svelte-tutorial/src/views/ui/Counter.svelte
<script lang="ts">
    import {type Counter} from '../../viewmodels/counter.svelte.js'

    let { counter }: { counter: Counter } = $props();
</script>

<div class="counter">
    <button type="button" onclick={counter.decrement}> -</button>
    <span>{counter.count}</span>
    <button type="button" onclick={counter.increment}> +</button>
</div>

<style lang="scss">
  :global {
    .counter {
      display: flex;
      gap: 0.5rem;
    }

    .counter + .counter {
      margin-top: 0.5rem;
    }
  }

  button {
    padding: 0.125rem 1rem;
  }
</style>

// counters/react-tutorial/src/views/Counter.tsx
import {useCallback, useEffect, useLayoutEffect, useState} from 'react'
import Button from "./ui/Button.tsx";

function Counter() {
    const [count, setCount] = useState(0)

    const decrement = useCallback(
        () => {
            setCount(count => count - 1)
        },
        []
    )

    const increment = useCallback(
        () => {
            setCount(count => count + 1)
        },
        []
    )

    return (
        <div>
            <Button onClick={decrement}> -</Button>
            <span>{count}</span>
            <Button onClick={increment}> +</Button>
        </div>
    )
}

export default Counter
